server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: code-jdbc
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        prefix:
        default-label: master
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.115:5432/tek_db?useUnicode=true&characterEncoding=UTF-8
    username: tek_user
    password: tek_user
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapping/*.xml
